name: build betterdiscord installer

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn dist
      - uses: actions/upload-artifact@v3
        with:
          name: BetterDiscord-Windows.exe
          path: dist/*.exe
